version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./__tests__:/app/__tests__
      - ./resources:/app/resources
      - ./settings.py:/app/settings.py
    environment:
      - PYTHONPATH=/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
