version: '3.8'
services:
  app:
    build: .
    container_name: app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
